source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
pod 'Eureka'
pod 'GeoJSON'
pod 'HanekeSwift'
pod 'Mapbox-iOS-SDK'
pod 'ObjectMapper'
pod 'SwiftyJSON'
