source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Siesta', '>=1.0-beta.6'
pod 'Alamofire'
pod 'Eureka'
pod 'GeoJSON'
pod 'HanekeSwift'
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/platform/ios/Mapbox-iOS-SDK.podspec'
pod 'ObjectMapper'
pod 'SwiftyJSON'
pod 'BubbleTransition', '~> 1.0.0'
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/ilyailya/BTNavigationDropdownMenu.git'
